# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1850, 930)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(2281, 1520))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 470, 171, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 470, 261, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 30, 311, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(140, 30, 171, 31))
        self.label_7.setObjectName("label_7")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(910, 610, 911, 261))
        self.listView.setObjectName("listView")
        self.imgEntrance = QtWidgets.QGroupBox(self.centralwidget)
        self.imgEntrance.setGeometry(QtCore.QRect(470, 100, 401, 351))
        self.imgEntrance.setMaximumSize(QtCore.QSize(2280, 1520))
        self.imgEntrance.setTitle("")
        self.imgEntrance.setObjectName("imgEntrance")
        self.lblImgEntrance = QtWidgets.QLabel(self.imgEntrance)
        self.lblImgEntrance.setGeometry(QtCore.QRect(-5, 2, 411, 351))
        self.lblImgEntrance.setText("")
        self.lblImgEntrance.setPixmap(QtGui.QPixmap("../AI/images/oto/detected/82.jpg"))
        self.lblImgEntrance.setScaledContents(True)
        self.lblImgEntrance.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImgEntrance.setWordWrap(False)
        self.lblImgEntrance.setObjectName("lblImgEntrance")
        self.camExit = QtWidgets.QGroupBox(self.centralwidget)
        self.camExit.setGeometry(QtCore.QRect(10, 540, 411, 351))
        self.camExit.setTitle("")
        self.camExit.setObjectName("camExit")
        self.imgExit = QtWidgets.QGroupBox(self.centralwidget)
        self.imgExit.setGeometry(QtCore.QRect(470, 540, 401, 351))
        self.imgExit.setTitle("")
        self.imgExit.setObjectName("imgExit")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(910, 90, 911, 321))
        self.groupBox_5.setMaximumSize(QtCore.QSize(2280, 1520))
        self.groupBox_5.setStyleSheet("font-size:20px;\n"
"color:rgb(170, 0, 0)")
        self.groupBox_5.setObjectName("groupBox_5")
        self.cmpIn2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.cmpIn2.setGeometry(QtCore.QRect(260, 90, 171, 141))
        self.cmpIn2.setStyleSheet("color:none\n"
"")
        self.cmpIn2.setTitle("")
        self.cmpIn2.setObjectName("cmpIn2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(180, 50, 261, 31))
        self.label_8.setStyleSheet("color:none;\n"
"font-size:none\n"
"")
        self.label_8.setObjectName("label_8")
        self.cmpIn1 = QtWidgets.QGroupBox(self.groupBox_5)
        self.cmpIn1.setGeometry(QtCore.QRect(40, 90, 171, 141))
        self.cmpIn1.setTitle("")
        self.cmpIn1.setObjectName("cmpIn1")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(650, 50, 261, 31))
        self.label_9.setStyleSheet("color:none;\n"
"font-size:none\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.cmpOut1 = QtWidgets.QGroupBox(self.groupBox_5)
        self.cmpOut1.setGeometry(QtCore.QRect(500, 90, 181, 141))
        self.cmpOut1.setTitle("")
        self.cmpOut1.setObjectName("cmpOut1")
        self.cmpOut2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.cmpOut2.setGeometry(QtCore.QRect(710, 90, 181, 141))
        self.cmpOut2.setTitle("")
        self.cmpOut2.setObjectName("cmpOut2")
        self.txtPlateIn = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtPlateIn.setGeometry(QtCore.QRect(160, 240, 151, 71))
        self.txtPlateIn.setObjectName("txtPlateIn")
        self.txtPlateOut = QtWidgets.QTextEdit(self.groupBox_5)
        self.txtPlateOut.setGeometry(QtCore.QRect(620, 240, 151, 71))
        self.txtPlateOut.setObjectName("txtPlateOut")
        self.check = QtWidgets.QGroupBox(self.groupBox_5)
        self.check.setGeometry(QtCore.QRect(400, 240, 120, 71))
        self.check.setTitle("")
        self.check.setObjectName("check")
        self.dteDate = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dteDate.setGeometry(QtCore.QRect(1190, 440, 591, 91))
        self.dteDate.setStyleSheet("font-size:32px;\n"
"")
        self.dteDate.setObjectName("dteDate")
        self.camEntrance = QtWidgets.QGroupBox(self.centralwidget)
        self.camEntrance.setGeometry(QtCore.QRect(20, 100, 401, 351))
        self.camEntrance.setTitle("")
        self.camEntrance.setObjectName("camEntrance")
        self.btnEntrance = QtWidgets.QPushButton(self.centralwidget)
        self.btnEntrance.setGeometry(QtCore.QRect(470, 60, 131, 31))
        self.btnEntrance.setObjectName("btnEntrance")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(470, 500, 131, 31))
        self.btnExit.setObjectName("btnExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Camera ra</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ảnh chụp xe ra</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ảnh chụp xe vào</span></p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Camera vào</span></p><p><br/></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "So sánh biển số xe vào ra"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Biển số xe vào</span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Biển số xe ra</span></p><p><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.dteDate.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btnEntrance.setText(_translate("MainWindow", "Chọn ảnh xe vào"))
        self.btnExit.setText(_translate("MainWindow", "Chọn ảnh xe ra"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
